<a href="https://colab.research.google.com/github/hongsoog/Effective-Python/blob/master/tensor_tutorial.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
%matplotlib inline


What is PyTorch?
================

It’s a Python-based scientific computing package targeted at two sets of
audiences:

-  A replacement for NumPy to use the power of GPUs
-  a deep learning research platform that provides maximum flexibility
   and speed

Getting Started
---------------

Tensors

Tensors are similar to NumPy’s ndarrays, with the addition being that
Tensors can also be used on a GPU to accelerate computing.



In [ ]:
from __future__ import print_function
import torch

In [ ]:
torch.__version__

'1.6.0+cu101'

In [ ]:
!nvidia-smi

Sun Aug  2 08:56:14 2020       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 450.57       Driver Version: 418.67       CUDA Version: 10.1     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   77C    P0    34W /  70W |    905MiB / 15079MiB |      0%      Default |
|                               |                      |                 ERR! |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

In [ ]:
torch.cuda.is_available()

True

In [ ]:
#List all the files in the current directory
!ls -lh

total 4.0K
drwxr-xr-x 1 root root 4.0K Jul 30 16:30 sample_data


What about all `*Tensor`s?
Press <esc> to get out of help

In [ ]:
torch.*Tensor?

In [ ]:
torch.nn.Module?

In [ ]:
torch.nn.Module??

#Vectors (1D Tensors)

torch.tensor infers the dtype automatically, while torch.Tensor returns a torch.FloatTensor. \\
I would recommend to stick to torch.tensor, which also has arguments like dtype, if you would like to change the type.

In [ ]:
# Creates a 1D tensor of integers 1 to 4
v = torch.tensor([1,2,3,4])
v

tensor([1, 2, 3, 4])

In [ ]:
v.dtype

torch.int64

In [ ]:
v.shape

torch.Size([4])

In [ ]:
v.size()

torch.Size([4])

In [ ]:
#Print number of dimensions (1D) and size of tensor
print(f'dim: {v.dim()}, size: {v.size()[0]}')

dim: 1, size: 4


In [ ]:
w = torch.tensor([1,0,2,0])
w

tensor([1, 0, 2, 0])

In [ ]:
# Element-wise multiplication
v * w

tensor([1, 0, 6, 0])

In [ ]:
# Scalar product : 1*1 + 2*0 + 3*2 + 4*0
v @ w

tensor(7)

In [ ]:
# inner product
torch.dot(v, w)

tensor(7)

In [ ]:
# In-place replacement of random number from 0 to 10
x = torch.Tensor(5).random_(10)
x

tensor([6., 4., 1., 6., 2.])

In [ ]:
print(f'first: {x[0]}, last: {x[-1]}')

first: 6.0, last: 2.0


In [ ]:
# Extract sub-Tensor [from:to) : Slicing
x[1 : 2]

tensor([4.])

In [ ]:
 x[1 : 2 + 1]

tensor([4., 1.])

In [ ]:
# Create a tensor with integers ranging from 1 to 5, excluding 5
# Note that torch.range is deprecated in favor of torch.arange().
v = torch.arange(1, 4 + 1)
v

tensor([1, 2, 3, 4])

In [ ]:
# Square all elements in the tensor
print(v.pow(2), v)

tensor([ 1,  4,  9, 16]) tensor([1, 2, 3, 4])


# Matrices (2D Tensors)

In [ ]:
# Square all elements in the tensor
m = torch.tensor([[2, 5, 3, 7],
                  [4, 2, 1, 9]])
m

tensor([[2, 5, 3, 7],
        [4, 2, 1, 9]])

In [ ]:
m.dim()

2

In [ ]:
m.size()

torch.Size([2, 4])

In [ ]:
m.shape

torch.Size([2, 4])

In [ ]:
print(m.size(0), m.size(1), m.size(), sep=' -- ')

2 -- 4 -- torch.Size([2, 4])


In [ ]:
# Return the total number of elements, hence num-el (number of elements)
m.numel()

8

In [ ]:
#Indexing row 0, column 2 (0-indexed)
m[0][2]

tensor(3)

In [ ]:
#Indexing row 0, column 2 (0-indexed)
m[0, 2]

tensor(3)

In [ ]:
#Indexing column 1, all rows (returns size 2)
print(m[:, 1], m[:,1].shape, sep=' , ')

tensor([5, 2]) , torch.Size([2])


In [ ]:
#Indexing column 1, all rows (returns size 2x1)
print(m[:, [1]], m[:, [1]].shape, sep=' , ')

tensor([[5],
        [2]]) , torch.Size([2, 1])


In [ ]:
#Indexing row 0, all column (returns size 4)
print(m[0, :], m[0, :].shape, sep=' , ')

tensor([2, 5, 3, 7]) , torch.Size([4])


In [ ]:
#Indexing row 0, all column (returns size 1x4)
print(m[[0], :], m[[0], :].shape, sep=' , ') 

tensor([[2, 5, 3, 7]]) , torch.Size([1, 4])


In [ ]:
# Create tensor (vector) of numbers from 1 to 5 (excluding 5)
v = torch.arange(1, 4 + 1)
v

tensor([1, 2, 3, 4])

In [ ]:
m

tensor([[2, 5, 3, 7],
        [4, 2, 1, 9]])

In [ ]:
# Scalar product (inner product)
m @ v

tensor([49, 47])

In [ ]:
# Scalar product (inner product)
# https://pytorch.org/docs/stable/generated/torch.dot.html
# torch.dot does not broadcast.
# torch.dot(v, m)

In [ ]:
# Calculated by 1*2 + 2*5 + 3*3 + 4*7
m[[0],:] @ v

tensor([49])

In [ ]:
m[0, :] @ v

tensor(49)

In [ ]:
# Add a random tneosr of size 2x4 to m
m + torch.rand(2, 4)

tensor([[2.7942, 5.5402, 3.8789, 7.9944],
        [4.7997, 2.1927, 1.7897, 9.5073]])

In [ ]:
# Subtract a random tensor of size 2x4 to m
m - torch.rand(2, 4)

tensor([[1.2357e+00, 4.1343e+00, 2.8551e+00, 6.9388e+00],
        [3.3158e+00, 1.2192e+00, 5.1732e-03, 8.3211e+00]])

In [ ]:
# Multiply a random tensor of size 2x4 to m
# Elementwise multiplication
m * torch.rand(2, 4)

tensor([[0.3648, 0.3135, 2.3288, 3.0495],
        [0.4904, 0.2957, 0.4664, 3.8138]])

In [ ]:
# Divide m by a random tensor of size 2x4 
m / torch.rand(2, 4)

tensor([[ 3.6296,  6.5758, 94.1643, 11.0354],
        [13.3094,  4.6920,  1.3089, 93.0710]])

In [ ]:
m.size()

torch.Size([2, 4])

In [ ]:
# Transpose tensor m, which is essentially 2x4 to 4x2
m.t()

tensor([[2, 4],
        [5, 2],
        [3, 1],
        [7, 9]])

In [ ]:
m.t().shape

torch.Size([4, 2])

In [ ]:
m.t().size()

torch.Size([4, 2])

In [ ]:
#Same as
m.transpose(0, 1)

tensor([[2, 4],
        [5, 2],
        [3, 1],
        [7, 9]])

In [ ]:
n = torch.tensor([[1, 1, 1, 1],
                  [0, 0, 0, 0]])
n

tensor([[1, 1, 1, 1],
        [0, 0, 0, 0]])

In [ ]:
n.shape

torch.Size([2, 4])

In [ ]:
# Matrix product (2x4 * 4x2 = 2x2)
print(m.shape)

mat = torch.matmul(m.t(), n)
print(mat)

print(m.t().mm(n))

torch.Size([2, 4])
tensor([[2, 2, 2, 2],
        [5, 5, 5, 5],
        [3, 3, 3, 3],
        [7, 7, 7, 7]])
tensor([[2, 2, 2, 2],
        [5, 5, 5, 5],
        [3, 3, 3, 3],
        [7, 7, 7, 7]])


# Constructor

<div class="alert alert-info"><h4>Note</h4><p>An uninitialized matrix is declared,
    but does not contain definite known
    values before it is used. When an
    uninitialized matrix is created,
    whatever values were in the allocated
    memory at the time will appear as the initial values.</p></div>



Construct a 5x3 matrix, uninitialized:



In [ ]:
x = torch.empty(5, 3)
x

tensor([[-3.6787e-08,  0.0000e+00,  5.6052e-45],
        [ 0.0000e+00,  7.0065e-45,  0.0000e+00],
        [ 2.8026e-45,  0.0000e+00,  4.2039e-45],
        [ 0.0000e+00,  1.4013e-45,  0.0000e+00],
        [ 9.8091e-45,  0.0000e+00,  1.2612e-44]])

In [ ]:
x.shape

torch.Size([5, 3])

In [ ]:
#prints dimensional space and sub-dimensions
print(f'point in a {x.numel()} dimensional space')
print(f'organized in {x.dim()} sub-dimensions')

point in a 15 dimensional space
organized in 2 sub-dimensions


Construct a randomly initialized matrix:



In [ ]:
x = torch.rand(5, 3)
x

tensor([[0.7709, 0.2292, 0.5699],
        [0.4995, 0.9723, 0.5015],
        [0.2566, 0.7544, 0.8485],
        [0.1942, 0.9746, 0.5516],
        [0.8125, 0.3460, 0.0738]])

In [ ]:
x.shape

torch.Size([5, 3])

In [ ]:
x.size()

torch.Size([5, 3])

Construct a matrix filled zeros and of dtype long:



Refer to https://pytorch.org/docs/stable/tensor_attributes.html#torch.torch.dtype 

In [ ]:
x = torch.zeros(5, 3, dtype=torch.long)
x

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])

In [ ]:
x = torch.zeros(5, 3, dtype=torch.float)
x

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [ ]:
x = torch.ones(5, 3)
print(x, x.dtype)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]) torch.float32


In [ ]:
x = torch.ones(5, 3, dtype=int)
print(x, x.dtype)

tensor([[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]]) torch.int64


Construct a tensor directly from data:



In [ ]:
x = torch.tensor([5.5, 3])
print(x, x.dtype, sep=' , ')

tensor([5.5000, 3.0000]) , torch.float32


or create a tensor based on an existing tensor. These methods
will reuse properties of the input tensor, e.g. dtype, unless
new values are provided by user



In [ ]:
# y = x.new_ones(5, 3, dtype=torch.double)      # new_* methods take in sizes
y = x.new_ones(5, 3)                            # new_* methods take in sizes
print(y, y.dtype, sep=' , ')

z = torch.randn_like(x, dtype=torch.float)    # override dtype!
print(z)                                      # result has the same size

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]) , torch.float32
tensor([-0.1964, -0.2432])


# Operations
There are multiple syntaxes for operations. In the following
example, we will take a look at the addition operation.

Addition: syntax 1


In [ ]:
x = torch.ones(5, 3)
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])


In [ ]:
y = torch.rand(5, 3)
print(x + y)

tensor([[1.5672, 1.1528, 1.4132],
        [1.8607, 1.2506, 1.7392],
        [1.8673, 1.9236, 1.0216],
        [1.3259, 1.3128, 1.8750],
        [1.5500, 1.1544, 1.3057]])


Addition: syntax 2



In [ ]:
print(torch.add(x, y))

tensor([[1.5672, 1.1528, 1.4132],
        [1.8607, 1.2506, 1.7392],
        [1.8673, 1.9236, 1.0216],
        [1.3259, 1.3128, 1.8750],
        [1.5500, 1.1544, 1.3057]])


Addition: providing an output tensor as argument



In [ ]:
result = torch.empty(5, 3)
print(result)

torch.add(x, y, out=result)
print(result)

tensor([[-3.6787e-08,  0.0000e+00,  1.4132e+00],
        [ 1.8607e+00,  1.2506e+00,  1.7392e+00],
        [ 1.8673e+00,  1.9236e+00,  1.0216e+00],
        [ 1.3259e+00,  1.3128e+00,  1.8750e+00],
        [ 1.5500e+00,  1.1544e+00,  1.3057e+00]])
tensor([[1.5672, 1.1528, 1.4132],
        [1.8607, 1.2506, 1.7392],
        [1.8673, 1.9236, 1.0216],
        [1.3259, 1.3128, 1.8750],
        [1.5500, 1.1544, 1.3057]])


## In-place 

Any operation that mutates a tensor in-place is post-fixed with an `_`. \\
For example: `x.add_(y)`, `x.copy_(y)`, `x.t_()`, `x.zero_()` , `x.random_(n)` will change x.



In [ ]:
# adds x to y
y.add_(x)
print(y)

tensor([[1.5672, 1.1528, 1.4132],
        [1.8607, 1.2506, 1.7392],
        [1.8673, 1.9236, 1.0216],
        [1.3259, 1.3128, 1.8750],
        [1.5500, 1.1544, 1.3057]])


In [ ]:
z = y.clone()
print(z)

tensor([[1.5672, 1.1528, 1.4132],
        [1.8607, 1.2506, 1.7392],
        [1.8673, 1.9236, 1.0216],
        [1.3259, 1.3128, 1.8750],
        [1.5500, 1.1544, 1.3057]])


In [ ]:
y.zero_()
print(y)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])


## Resizing
If you want to resize/reshape tensor, you can use ``torch.view``:

Refer to : 
- [reshape vs. view](https://discuss.pytorch.org/t/difference-between-view-reshape-and-permute/54157)
- [Contiguous tensor](https://stackoverflow.com/questions/26998223/what-is-the-difference-between-contiguous-and-non-contiguous-arrays/26999092#26999092)

In short, 
`torch.reshape` may copy the original tensor or not while `torch.view` shares the original one.


In [ ]:
x = torch.rand(4, 4)
print(x.shape, x.numel(), sep=' , ')

y = x.view(16)
print(y.shape, y, sep=' , ')

torch.Size([4, 4]) , 16
torch.Size([16]) , tensor([0.5434, 0.9969, 0.0386, 0.6285, 0.9983, 0.0131, 0.4822, 0.4127, 0.9562,
        0.8341, 0.5826, 0.3958, 0.0661, 0.0151, 0.4560, 0.1899])


In [ ]:
z = x.view(-1, 8) # the size -1 is inffered from other dimensions
print(x.shape, z.shape)

torch.Size([4, 4]) torch.Size([2, 8])


If you have a one element tensor, use ``.item()`` to get the value as a
Python number



In [ ]:
x = torch.randn(1)
print(x)
print(x.item())

tensor([2.2143])
2.2143375873565674


In [ ]:
x = torch.randn(1)
print(x)
print(x.item())

tensor([0.7410])
0.7410443425178528


## Broadcasting

In short, if a PyTorch operation supports broadcast, then its Tensor arguments can be automatically expanded to be of equal sizes (without making copies of the data).

![대체 텍스트](https://cdn-images-1.medium.com/max/1000/0*lo4N0ZZvMFc903Ab.png)


### General semantics 

Two tensors are “broadcastable” if the following rules hold:

- Each tensor has at least one dimension.

- When iterating over the dimension sizes, starting at the trailing dimension, the dimension sizes must either be 
    1. equal
    2. one of them is 1 
    3. one of them does not exist.

In [ ]:
# same shapes are always broadcastable (i.e. the above rules always hold)
x=torch.empty(5,7,3)
y=torch.empty(5,7,3)


x=torch.empty((0,))
y=torch.empty(2,2)
# x and y are not broadcastable, because x does not have at least 1 dimension

# can line up trailing dimensions
x=torch.empty(5,3,4,1)
y=torch.empty(  3,1,1)
z = x + y
print(z.shape)
# x and y are broadcastable.
# 1st trailing dimension: both have size 1
# 2nd trailing dimension: y has size 1
# 3rd trailing dimension: x size == y size
# 4th trailing dimension: y dimension doesn't exist

# but:
x=torch.empty(5,2,4,1)
y=torch.empty(  3,1,1)
# x and y are not broadcastable, because in the 3rd trailing dimension 2 != 3

torch.Size([5, 3, 4, 1])


In [ ]:
# Example 1. : one of them does not exist
x = torch.arange(3) #( , 3)
y = torch.tensor(5) #( ,  )
print(x.shape, y.shape)
print(x, y)

print(x + y)

torch.Size([3]) torch.Size([])
tensor([0, 1, 2]) tensor(5)
tensor([5, 6, 7])


In [ ]:
#Example 2. : one of them is 1 + one of them doe not exist
x = torch.arange(3).view(3,1) # (3,1)
y = torch.arange(3)           # ( ,3)
print(x.shape, y.shape)

print(x + y)

torch.Size([3, 1]) torch.Size([3])
tensor([[0, 1, 2],
        [1, 2, 3],
        [2, 3, 4]])


In [ ]:
#Example 3. : equal + one of them is 1 + one of them doe not exist
x = torch.zeros(2, 2, 3)  # (2, 2, 3)
y = torch.ones(1, 3)      # ( , 1, 3)
print(x.shape, y.shape)

print(x + y, (x+y).shape)

torch.Size([2, 2, 3]) torch.Size([1, 3])
tensor([[[1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.]]]) torch.Size([2, 2, 3])


**Read later:**


  100+ Tensor operations, including transposing, indexing, slicing,
  mathematical operations, linear algebra, random numbers, etc.,
  are described
  `here <https://pytorch.org/docs/torch>`_.




# NumPy Bridge


Converting a Torch Tensor to a NumPy array and vice versa is a breeze.

The Torch Tensor and NumPy array will share their underlying memory
locations (if the Torch Tensor is on CPU), and changing one will change
the other.

Converting a Torch Tensor to a NumPy Array

In [ ]:
a = torch.ones(5)
print(a)

tensor([1., 1., 1., 1., 1.])


In [ ]:
b = a.numpy()
print(b)

[1. 1. 1. 1. 1.]


See how the numpy array changed in value.



In [ ]:
a.add_(1)
print(a)

tensor([2., 2., 2., 2., 2.])


In [ ]:
a.add_(1)
print(a)
print(b)

tensor([3., 3., 3., 3., 3.])
[3. 3. 3. 3. 3.]


Converting NumPy Array to Torch Tensor

See how changing the np array changed the Torch Tensor automatically



In [ ]:
import numpy as np

a = np.ones(5)
b = torch.from_numpy(a)
print(a, b)

np.add(a, 1, out=a)
print(a, b)

[1. 1. 1. 1. 1.] tensor([1., 1., 1., 1., 1.], dtype=torch.float64)
[2. 2. 2. 2. 2.] tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


All the Tensors on the CPU except a CharTensor support converting to
NumPy and back.


# CUDA Tensors

Tensors can be moved onto any device using the ``.to`` method.


In [ ]:
x = torch.zeros(2,2)
print("x's device : ", x.device)

# let us run this cell only if CUDA is available
# We will use ``torch.device`` objects to move tensors in and out of GPU
if torch.cuda.is_available():
    device = torch.device("cuda")           # a CUDA device object
    y = torch.ones_like(x, device=device)   # directly create a tensor on GPU
    print("y's device : ", y.device)        

    x = x.to(device)                        # or just use strings ``.to("cuda")``
    print("x's device : ", x.device)

    z = x + y
    print(z)
    print(z.to("cpu", torch.double))        # ``.to`` can also change dtype together!

x's device :  cpu
y's device :  cuda:0
x's device :  cuda:0
tensor([[1., 1.],
        [1., 1.]], device='cuda:0')
tensor([[1., 1.],
        [1., 1.]], dtype=torch.float64)


# AutoGrad

Autograd: Automatic Differentiation
===================================

Central to all neural networks in PyTorch is the ``autograd`` package.
Let’s first briefly visit this, and we will then go to training our
first neural network.


The ``autograd`` package provides automatic differentiation for all operations
on Tensors. It is a define-by-run framework, which means that your backprop is
defined by how your code is run, and that every single iteration can be
different.

Let us see this in more simple terms with some examples.

Tensor
--------

``torch.Tensor`` is the central class of the package. If you set its attribute
``.requires_grad`` as ``True``, it starts to track all operations on it. When
you finish your computation you can call ``.backward()`` and have all the
gradients computed automatically. The gradient for this tensor will be
accumulated into ``.grad`` attribute.

To stop a tensor from tracking history, you can call ``.detach()`` to detach
it from the computation history, and to prevent future computation from being
tracked.

To prevent tracking history (and using memory), you can also wrap the code block
in ``with torch.no_grad():``. This can be particularly helpful when evaluating a
model because the model may have trainable parameters with
``requires_grad=True``, but for which we don't need the gradients.

There’s one more class which is very important for autograd
implementation - a ``Function``.

``Tensor`` and ``Function`` are interconnected and build up an acyclic
graph, that encodes a complete history of computation. Each tensor has
a ``.grad_fn`` attribute that references a ``Function`` that has created
the ``Tensor`` (except for Tensors created by the user - their
``grad_fn is None``).

If you want to compute the derivatives, you can call ``.backward()`` on
a ``Tensor``. If ``Tensor`` is a scalar (i.e. it holds a one element
data), you don’t need to specify any arguments to ``backward()``,
however if it has more elements, you need to specify a ``gradient``
argument that is a tensor of matching shape.





Create a tensor and set ``requires_grad=True`` to track computation with it



In [ ]:
x = torch.ones(2, 2, requires_grad=True)
print(x)

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)


Do a tensor operation:

In [ ]:
y = x + 2
print(y)

tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>)


``y`` was created as a result of an operation, so it has a ``grad_fn``.

In [ ]:
print(y.grad_fn)

In [ ]:
z = y * y * 3
out = z.mean()

print(z)
print(out)

tensor([[27., 27.],
        [27., 27.]], grad_fn=<MulBackward0>)
tensor(27., grad_fn=<MeanBackward0>)


``.requires_grad_( ... )`` changes an existing Tensor's ``requires_grad``
flag in-place. The input flag defaults to ``False`` if not given.



In [ ]:
a = torch.randn(2, 2)
a = ((a * 3) / (a - 1))
print(a.requires_grad)

False


In [ ]:
a.requires_grad_(True)
print(a.requires_grad)

True


In [ ]:
b = (a * a).sum()
print(b.grad_fn)

Gradients
---------
Let's backprop now.
Because ``out`` contains a single scalar, ``out.backward()`` is
equivalent to ``out.backward(torch.tensor(1.))``.



In [ ]:
out.backward()

Print gradients $\frac{\partial o}{\partial x}$




In [ ]:
print(x.grad)

tensor([[4.5000, 4.5000],
        [4.5000, 4.5000]])


You should have got a matrix of ``4.5``. Let’s call the ``out``
*Tensor* “$o$”.
We have that $o = \frac{1}{4}\sum_i z_i$,
$z_i = 3(x_i+2)^2$ and $z_i\bigr\rvert_{x_i=1} = 27$.
Therefore,
$\frac{\partial o}{\partial x_i} = \frac{3}{2}(x_i+2)$, hence
$\frac{\partial o}{\partial x_i}\bigr\rvert_{x_i=1} = \frac{9}{2} = 4.5$.



You can also stop autograd from tracking history on Tensors
with ``.requires_grad=True`` either by wrapping the code block in
``with torch.no_grad():``



In [ ]:
print(x.requires_grad)
print((x**2).requires_grad)

with torch.no_grad():
    print((x**2).requires_grad)

True
True
False


Or by using ``.detach()`` to get a new Tensor with the same
content but that does not require gradients:



In [ ]:
print(x.requires_grad)
print(x.grad)

True
tensor([[4.5000, 4.5000],
        [4.5000, 4.5000]])


In [ ]:
y = x.detach()
print(y.requires_grad)
print(y.grad)

False
None


In [ ]:
print(x.eq(y).all())

tensor(True)
